### ISSUE TITLE
VelocityRender 'stuck' in DisplayHierachy.expand()

### ISSUE THREAD

**Issue by skwlilac** [epimorphics/elda#124]
Rendering using the velocity renderer with a `&_properties=*.*` parameter present can get the velocity renderer stuck.

I've prepared a test case in the `bwq-lda` project branch `test-case` which as a single API endpoint, viewer and a full set of short-names which could be pruned.

The default html render is set to the velocity renderer. The following reference fails to return a response (stuck in the render).

`http://localhost/elda/def?_properties=*.*`

For comparison

`http://localhost/elda/def.xhtml?_properties=*.*`

will does produce a response.

I have paused the render in a debugger and found that its 'stuck' in `DisplayHierarchy.expand()`. Inspection of `context.queue` showed that it had ~648000 entries.

**Comment by ijdickinson** [comment]
Confirm I can reproduce the problem. I suspect the root cause is in the logic that detecs and breaks loops in the graph, *unless* the node is on an explicit path requested by the user. This was a requested feature, to ensure that if the user requested `_properties=a.b.c`, and `b` happened to be a previously seen node, it would nevertheless continue to expand the tree to `c`. The XSLT renderer doesn't do this.

In this case, the requested path is `*.*`, which I can imagine might causes the loop-breaking algorithm some headaches.

**Comment by ijdickinson** [comment]
I've committed a fix for this issue, please try it. You'll need Elda 1.3.6-SNAPSHOT

**Comment by skwlilac** [comment]
Yes, that's fixed it. Thank you.
