### ISSUE TITLE
standalone JAR doesn't work

### ISSUE THREAD

**Issue by rwalkerands** [epimorphics/elda#130]
The generated standalone JAR for 1.3.3 "works", but the ones for 1.3.4 and 1.3.5 don't.
You get a 404 for every URL you try -- and even the generation of the 404 page is broken!

E.g., for 1.3.5, output for _any_ request of the form `/standalone/...` shows this:

    SEVERE: Exception Processing ErrorPage[errorCode=404, location=/_errors/404.html] java.lang.NullPointerException
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:456)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:327)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:193)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:929)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1002)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:585)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ehedgehog** [comment]
Hmm. The standalone jar fails (I'm surprised that wasn't caught at
release time) but the internal server project works under Eclipse.
Which will make it harder to track failures.

**Comment by ehedgehog** [comment]
Looks like (thanks, Mr Git Bisect) it's ironically this commit:

290adb5a05fd11677e70f9421db556da7f18a8e9 is the first bad commit
commit 290adb5a05fd11677e70f9421db556da7f18a8e9
Author: Chris Dollin <ehog.hedge@googlemail.com>
Date:   Wed Dec 3 16:16:29 2014 +0000

    Applied error-pages fix to standalone.

This is a notion of "fix" that had not previously
occurred to me.

**Comment by ehedgehog** [comment]
standalone's web.xml had been configured to use filters. Changing to
servlets allows the usual URLs to work, but now any 404 produces the
default Topmcat page. More investigation required.

**Comment by ehedgehog** [comment]
The branch fix-web-xml-error has the filter-to-servlet patch.

**Comment by ehedgehog** [comment]
Investigation revealed that there were two errors in the use of error-page in the web.xml.
One was that the error page location was mis-named (failure to catch up with earlier
reorganisation of the webapp). The other more subtle error was that the explicit default
servlet did not bind the error page location, so that attempts to use it (which are handled
by treating it as a servlet request) failed. Adding the /error_pages/* URL to the default
servlet mapping fixed that.

The (current) Elda standalone is built using the maven tomcat plugin. It appears that this
will only run Elda when Jersey is configured as a servlet rather than a filter -- configured as
a filter all we get from a legal endpoint (eg /standalone/again/games) is the custom error
page. It's clear from using the part of the web.xml and the registration messages that
the standalone jar generates when it starts that the endpoints have all been configured
but that for some reason tomcat doesn't recognise them.

With Jersey configured as a servlet, then legal URLs work, as indeed do illegal non-404
URLs, for instance having unrecognised reserved parameters such as ?_rhubarb=tofee.
However 404-generating URLs generate a 404 response with no content -- not the
custom content nor the standard Tomcat 404 page. This /may/ be because no
FilterForwardOn404 can be applied -- putting it within a servlet doesn't seem to 
work, while it work (or appears to) when Jersey is configured as a filter.

Having correct URLs work and missing ones give a non-custom blank-page 404 
is an uncomfortable compromise but the best I can offer at the moment.

[Running Elda using the internal Tomcat suffers the same problem with the
servlet configuration.]

**Comment by ehedgehog** [comment]
Closed in 1.3.12
